/**
 * Executable schema generated by Grats (https://grats.capt.dev)
 * Do not manually edit. Regenerate by running `npx grats`.
 */

import { GraphQLSchema, GraphQLDirective, DirectiveLocation, GraphQLNonNull, GraphQLInt, specifiedDirectives, GraphQLObjectType, GraphQLString, GraphQLID, GraphQLBoolean, GraphQLInputObjectType, GraphQLEnumType, GraphQLList, GraphQLFloat } from "graphql";
import { libraryScan as queryLibraryScanResolver, libraryScanCancel as mutationLibraryScanCancelResolver, libraryScanStart as mutationLibraryScanStartResolver, libraryScanSubscription as subscriptionLibraryScanResolver } from "./../library-scan.js";
import { ping as queryPingResolver, noop as mutationNoopResolver } from "./../root.js";
import { url as trackUrlResolver } from "./../track.js";
import { track as queryTrackResolver, tracks as queryTracksResolver } from "./../track-queries.js";
import { trackManifestSubscription as subscriptionTrackManifestResolver } from "./../track-manifest.js";
export function getSchema(): GraphQLSchema {
    const LibraryScanType: GraphQLObjectType = new GraphQLObjectType({
        name: "LibraryScan",
        description: "Snapshot of an ongoing or completed library scan.",
        fields() {
            return {
                errorMessage: {
                    description: "Human-readable summary of errors encountered, or null when no errors have been recorded.",
                    name: "errorMessage",
                    type: GraphQLString
                },
                errorsTotal: {
                    description: "Files that failed to parse or upsert.",
                    name: "errorsTotal",
                    type: new GraphQLNonNull(GraphQLInt)
                },
                filesTotal: {
                    description: "Total files discovered on disk for this scan. Null until the file walk has finished \u2014 clients should render an indeterminate progress state in that case.",
                    name: "filesTotal",
                    type: GraphQLInt
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                isCompleted: {
                    description: "True once the scan has finished (successfully or not).",
                    name: "isCompleted",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                scannedTotal: {
                    description: "Files successfully parsed and upserted so far.",
                    name: "scannedTotal",
                    type: new GraphQLNonNull(GraphQLInt)
                }
            };
        }
    });
    const DurationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Duration",
        description: "A length of time, expressed in whole seconds.",
        fields() {
            return {
                formatted: {
                    description: "Human-readable form, e.g. `\"05:32\"` or `\"1:02:14\"` for spans at least an hour long.",
                    name: "formatted",
                    type: new GraphQLNonNull(GraphQLString)
                },
                seconds: {
                    name: "seconds",
                    type: new GraphQLNonNull(GraphQLInt)
                }
            };
        }
    });
    const FormatLossyType: GraphQLEnumType = new GraphQLEnumType({
        description: "Codec the lossy delivery path uses.",
        name: "FormatLossy",
        values: {
            MP3: {
                value: "MP3"
            },
            OPUS: {
                value: "OPUS"
            }
        }
    });
    const QualityType: GraphQLEnumType = new GraphQLEnumType({
        description: "Coarse playback quality. `MIN` / `LOW` / `MEDIUM` / `HIGH` map to lossy presets in ascending bitrate; `MAX` asks for lossless when the source is lossless and the highest lossy preset (in `formatLossy`) when it isn't.",
        name: "Quality",
        values: {
            HIGH: {
                value: "HIGH"
            },
            LOW: {
                value: "LOW"
            },
            MAX: {
                value: "MAX"
            },
            MEDIUM: {
                value: "MEDIUM"
            },
            MIN: {
                value: "MIN"
            }
        }
    });
    const TrackFormatType: GraphQLInputObjectType = new GraphQLInputObjectType({
        description: "How the client wants the track delivered. `formatLossy` is always required \u2014 even when `quality: MAX`, the server falls through to a lossy stream for non-lossless sources, so it always needs a codec to fall back to.",
        name: "TrackFormat",
        fields() {
            return {
                formatLossy: {
                    name: "formatLossy",
                    type: new GraphQLNonNull(FormatLossyType)
                },
                quality: {
                    name: "quality",
                    type: new GraphQLNonNull(QualityType)
                }
            };
        }
    });
    const TrackType: GraphQLObjectType = new GraphQLObjectType({
        name: "Track",
        description: "A single audio file in the library.",
        fields() {
            return {
                album: {
                    name: "album",
                    type: GraphQLString
                },
                artist: {
                    name: "artist",
                    type: GraphQLString
                },
                discNumber: {
                    name: "discNumber",
                    type: GraphQLInt
                },
                duration: {
                    name: "duration",
                    type: new GraphQLNonNull(DurationType)
                },
                format: {
                    description: "Container plus codec, lower-cased and space-separated, e.g. `\"ogg vorbis\"`, `\"mp3\"`, `\"webm opus\"`.",
                    name: "format",
                    type: new GraphQLNonNull(GraphQLString)
                },
                id: {
                    name: "id",
                    type: new GraphQLNonNull(GraphQLID)
                },
                isLossless: {
                    description: "Whether the source file is a lossless format (flac, alac, wav, etc.).",
                    name: "isLossless",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                sourceFormat: {
                    description: "Source codec of the file on disk, lower-cased, e.g. `\"flac\"`, `\"alac\"`, `\"mp3\"`, `\"opus\"`.",
                    name: "sourceFormat",
                    type: new GraphQLNonNull(GraphQLString)
                },
                title: {
                    name: "title",
                    type: GraphQLString
                },
                trackNumber: {
                    name: "trackNumber",
                    type: GraphQLInt
                },
                url: {
                    description: "Signed URL the client should `GET` (with `Range:` headers) to stream this track. The URL bakes in `format` so a single URL is reusable for the lifetime of a playback session.\n\nDefaults to `{ quality: MAX, formatLossy: OPUS }`.",
                    name: "url",
                    type: new GraphQLNonNull(GraphQLString),
                    args: {
                        format: {
                            type: TrackFormatType
                        }
                    },
                    resolve(source, args) {
                        return trackUrlResolver(source, args.format);
                    }
                },
                year: {
                    name: "year",
                    type: GraphQLString
                }
            };
        }
    });
    const TrackEdgeType: GraphQLObjectType = new GraphQLObjectType({
        name: "TrackEdge",
        description: "A single entry in a `TrackConnection`.",
        fields() {
            return {
                cursor: {
                    description: "Cursor for paginating relative to this edge; equal to the track's `id`.",
                    name: "cursor",
                    type: new GraphQLNonNull(GraphQLID)
                },
                node: {
                    name: "node",
                    type: new GraphQLNonNull(TrackType)
                }
            };
        }
    });
    const PageInfoType: GraphQLObjectType = new GraphQLObjectType({
        name: "PageInfo",
        description: "Boundary metadata for a `TrackConnection`.",
        fields() {
            return {
                endCursor: {
                    description: "Cursor of the last edge on the current page, or `null` for an empty page.",
                    name: "endCursor",
                    type: GraphQLID
                },
                hasNextPage: {
                    description: "True when more tracks exist after the current page in the sort order.",
                    name: "hasNextPage",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                hasPreviousPage: {
                    description: "True when more tracks exist before the current page in the sort order.",
                    name: "hasPreviousPage",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                startCursor: {
                    description: "Cursor of the first edge on the current page, or `null` for an empty page.",
                    name: "startCursor",
                    type: GraphQLID
                }
            };
        }
    });
    const TrackConnectionType: GraphQLObjectType = new GraphQLObjectType({
        name: "TrackConnection",
        description: "One page of a Relay-style traversal over the track library.",
        fields() {
            return {
                edges: {
                    name: "edges",
                    type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(TrackEdgeType)))
                },
                pageInfo: {
                    name: "pageInfo",
                    type: new GraphQLNonNull(PageInfoType)
                },
                totalCount: {
                    description: "Total number of tracks in the library, ignoring pagination arguments.",
                    name: "totalCount",
                    type: new GraphQLNonNull(GraphQLInt)
                }
            };
        }
    });
    const QueryType: GraphQLObjectType = new GraphQLObjectType({
        name: "Query",
        fields() {
            return {
                libraryScan: {
                    description: "The current library scan, if one is in progress or recently completed within the server's grace window. Null when no scan has run recently.",
                    name: "libraryScan",
                    type: LibraryScanType,
                    resolve() {
                        return queryLibraryScanResolver();
                    }
                },
                ping: {
                    description: "Returns the literal string `\"pong\"`. Useful as a liveness probe.",
                    name: "ping",
                    type: GraphQLString,
                    resolve() {
                        return queryPingResolver();
                    }
                },
                track: {
                    description: "Look up a single track by id. Returns `null` when no track with that id exists.",
                    name: "track",
                    type: TrackType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return queryTrackResolver(args.id);
                    }
                },
                tracks: {
                    description: "List the library in Relay-cursor pagination order: by `artist`, `album`, `discNumber`, `trackNumber`, then `id` for stability. Supply exactly one of `first`/`last` and at most one of `after`/`before`.",
                    name: "tracks",
                    type: TrackConnectionType,
                    args: {
                        after: {
                            type: GraphQLString
                        },
                        before: {
                            type: GraphQLString
                        },
                        first: {
                            type: GraphQLInt
                        },
                        last: {
                            type: GraphQLInt
                        }
                    },
                    resolve(_source, args) {
                        return queryTracksResolver(args.first, args.last, args.after, args.before);
                    }
                }
            };
        }
    });
    const VoidType: GraphQLObjectType = new GraphQLObjectType({
        name: "Void",
        description: "Empty payload returned by mutations that have nothing meaningful to report.",
        fields() {
            return {
                _: {
                    name: "_",
                    type: GraphQLBoolean
                }
            };
        }
    });
    const MutationType: GraphQLObjectType = new GraphQLObjectType({
        name: "Mutation",
        fields() {
            return {
                libraryScanCancel: {
                    description: "Requests cancellation of the named in-progress scan. No-op when the scan is unknown or already completed.",
                    name: "libraryScanCancel",
                    type: new GraphQLNonNull(VoidType),
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    resolve(_source, args) {
                        return mutationLibraryScanCancelResolver(args);
                    }
                },
                libraryScanStart: {
                    description: "Triggers a full scan of the configured library. Returns immediately with `filesTotal: null`; the file walk and parsing run in the background. Observe progress via `Subscription.libraryScan`.",
                    name: "libraryScanStart",
                    type: new GraphQLNonNull(LibraryScanType),
                    resolve() {
                        return mutationLibraryScanStartResolver();
                    }
                },
                noop: {
                    description: "Does nothing.",
                    name: "noop",
                    type: new GraphQLNonNull(VoidType),
                    resolve() {
                        return mutationNoopResolver();
                    }
                }
            };
        }
    });
    const TrackManifestChunkType: GraphQLObjectType = new GraphQLObjectType({
        name: "TrackManifestChunk",
        description: "One finalised chunk of the encoded stream. Clients pick the chunk whose byte range covers a target seek time by binary-searching `endSeconds`, then issue a `Range: bytes=byteStart-byteEnd-1` request against the playback URL.",
        fields() {
            return {
                byteEnd: {
                    description: "Exclusive end byte offset.",
                    name: "byteEnd",
                    type: new GraphQLNonNull(GraphQLFloat)
                },
                byteStart: {
                    description: "Inclusive start byte offset.",
                    name: "byteStart",
                    type: new GraphQLNonNull(GraphQLFloat)
                },
                endSeconds: {
                    description: "Cumulative encoded end time of this chunk, in seconds. Strictly increasing across the `chunks` array.",
                    name: "endSeconds",
                    type: new GraphQLNonNull(GraphQLFloat)
                }
            };
        }
    });
    const TrackManifestInitType: GraphQLObjectType = new GraphQLObjectType({
        name: "TrackManifestInit",
        description: "Byte range of the init segment in the encoded `.bin`. Clients fetch this range first and prepend it to the SourceBuffer before appending any chunk. Null on containers that have no init segment (mp3).",
        fields() {
            return {
                byteEnd: {
                    description: "Exclusive end byte offset.",
                    name: "byteEnd",
                    type: new GraphQLNonNull(GraphQLFloat)
                },
                byteStart: {
                    description: "Inclusive start byte offset.",
                    name: "byteStart",
                    type: new GraphQLNonNull(GraphQLFloat)
                }
            };
        }
    });
    const TrackManifestType: GraphQLObjectType = new GraphQLObjectType({
        name: "TrackManifest",
        description: "Live manifest snapshot for a `(track, quality, format)` cache entry. Grows monotonically as the encoder produces chunks: subscribers receive an initial snapshot of whatever's ready, then a fresh snapshot whenever the index changes, terminating with `done: true`.",
        fields() {
            return {
                chunkDurationSeconds: {
                    description: "Nominal chunk duration the encoder is configured for, in seconds. Actual `endSeconds` deltas may run a few % longer (mp3 windows close on the next frame boundary after crossing the threshold).",
                    name: "chunkDurationSeconds",
                    type: new GraphQLNonNull(GraphQLFloat)
                },
                chunks: {
                    description: "Finalised chunks, in order.",
                    name: "chunks",
                    type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(TrackManifestChunkType)))
                },
                done: {
                    description: "True once the encoder has finished and the trailing chunk has been emitted. After this, no more snapshots will arrive.",
                    name: "done",
                    type: new GraphQLNonNull(GraphQLBoolean)
                },
                durationSeconds: {
                    description: "Cumulative encoded duration so far, equal to `chunks[last].endSeconds` or `0` when no chunks have landed yet.",
                    name: "durationSeconds",
                    type: new GraphQLNonNull(GraphQLFloat)
                },
                init: {
                    description: "Init-segment byte range. `null` for mp3, and `null` for fmp4 until the first fragment boundary has been observed.",
                    name: "init",
                    type: TrackManifestInitType
                }
            };
        }
    });
    const SubscriptionType: GraphQLObjectType = new GraphQLObjectType({
        name: "Subscription",
        fields() {
            return {
                libraryScan: {
                    description: "Streams snapshots of the named scan every second until it completes. Closes the stream once the scan finishes normally (after yielding a final snapshot with `isCompleted: true`), or yields a single `null` and closes when the scan is cancelled or evicted.",
                    name: "libraryScan",
                    type: LibraryScanType,
                    args: {
                        id: {
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    subscribe(_source, args) {
                        return subscriptionLibraryScanResolver(args);
                    },
                    resolve(payload) {
                        return payload;
                    }
                },
                trackManifest: {
                    description: "Stream manifest snapshots for `(trackId, quality, format)`. The same `(quality, format)` values the client baked into its signed playback URL drive cache-entry selection on the server, so the manifest describes exactly the bytes the playback route will serve.\n\nEmits at most once per second while the encoder runs, then a final snapshot when it finishes. For already-warm cache entries (or for tracks served by passthrough) the subscription emits a single `done: true` snapshot and completes.",
                    name: "trackManifest",
                    type: new GraphQLNonNull(TrackManifestType),
                    args: {
                        format: {
                            description: "Same `(quality, formatLossy)` the client baked into its signed playback URL.",
                            type: new GraphQLNonNull(TrackFormatType)
                        },
                        trackId: {
                            description: "Track id.",
                            type: new GraphQLNonNull(GraphQLID)
                        }
                    },
                    subscribe(_source, args) {
                        return subscriptionTrackManifestResolver(args);
                    },
                    resolve(payload) {
                        return payload;
                    }
                }
            };
        }
    });
    return new GraphQLSchema({
        directives: [...specifiedDirectives, new GraphQLDirective({
                name: "constraint",
                locations: [DirectiveLocation.ARGUMENT_DEFINITION],
                description: "Restricts a numeric argument to the inclusive range [min, max].",
                args: {
                    min: {
                        type: new GraphQLNonNull(GraphQLInt)
                    },
                    max: {
                        type: new GraphQLNonNull(GraphQLInt)
                    }
                }
            })],
        query: QueryType,
        mutation: MutationType,
        subscription: SubscriptionType,
        types: [FormatLossyType, QualityType, TrackFormatType, DurationType, LibraryScanType, MutationType, PageInfoType, QueryType, SubscriptionType, TrackType, TrackConnectionType, TrackEdgeType, TrackManifestType, TrackManifestChunkType, TrackManifestInitType, VoidType]
    });
}
