/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Album': { kind: 'OBJECT'; name: 'Album'; fields: { 'artists': { name: 'artists'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Artist'; ofType: null; }; }; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'AlbumConnection': { kind: 'OBJECT'; name: 'AlbumConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AlbumEdge'; ofType: null; }; }; }; } }; 'totalCount': { name: 'totalCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'AlbumEdge': { kind: 'OBJECT'; name: 'AlbumEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Album'; ofType: null; }; } }; }; };
    'Artist': { kind: 'OBJECT'; name: 'Artist'; fields: { 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'ArtistConnection': { kind: 'OBJECT'; name: 'ArtistConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ArtistEdge'; ofType: null; }; }; }; } }; 'totalCount': { name: 'totalCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'ArtistEdge': { kind: 'OBJECT'; name: 'ArtistEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Artist'; ofType: null; }; } }; }; };
    'ArtistInitial': { kind: 'OBJECT'; name: 'ArtistInitial'; fields: { 'label': { name: 'label'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'offset': { name: 'offset'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'ArtistSynonym': { kind: 'OBJECT'; name: 'ArtistSynonym'; fields: { 'artist': { name: 'artist'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'synonym': { name: 'synonym'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Boolean': unknown;
    'DeliveryTier': { kind: 'OBJECT'; name: 'DeliveryTier'; fields: { 'bitrateKbps': { name: 'bitrateKbps'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'quality': { name: 'quality'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Quality'; ofType: null; }; } }; }; };
    'Duration': { kind: 'OBJECT'; name: 'Duration'; fields: { 'formatted': { name: 'formatted'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'seconds': { name: 'seconds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Float': unknown;
    'ID': unknown;
    'Int': unknown;
    'LibraryScan': { kind: 'OBJECT'; name: 'LibraryScan'; fields: { 'errorMessage': { name: 'errorMessage'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'errorsTotal': { name: 'errorsTotal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'filesTotal': { name: 'filesTotal'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isCompleted': { name: 'isCompleted'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'scannedTotal': { name: 'scannedTotal'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'artistSynonymCreate': { name: 'artistSynonymCreate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ArtistSynonym'; ofType: null; }; } }; 'artistSynonymDelete': { name: 'artistSynonymDelete'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Void'; ofType: null; }; } }; 'artistSynonymUpdate': { name: 'artistSynonymUpdate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ArtistSynonym'; ofType: null; }; } }; 'libraryScanCancel': { name: 'libraryScanCancel'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Void'; ofType: null; }; } }; 'libraryScanStart': { name: 'libraryScanStart'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'LibraryScan'; ofType: null; }; } }; 'noop': { name: 'noop'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Void'; ofType: null; }; } }; 'trackUpdate': { name: 'trackUpdate'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Track'; ofType: null; }; } }; }; };
    'PageInfo': { kind: 'OBJECT'; name: 'PageInfo'; fields: { 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; } }; }; };
    'Quality': { name: 'Quality'; enumValues: 'HIGH' | 'LOW' | 'MAX' | 'MEDIUM' | 'MIN'; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'artistIndex': { name: 'artistIndex'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ArtistInitial'; ofType: null; }; }; } }; 'libraryScan': { name: 'libraryScan'; type: { kind: 'OBJECT'; name: 'LibraryScan'; ofType: null; } }; 'ping': { name: 'ping'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'search': { name: 'search'; type: { kind: 'OBJECT'; name: 'Search'; ofType: null; } }; 'track': { name: 'track'; type: { kind: 'OBJECT'; name: 'Track'; ofType: null; } }; 'tracks': { name: 'tracks'; type: { kind: 'OBJECT'; name: 'TrackConnection'; ofType: null; } }; }; };
    'Search': { kind: 'OBJECT'; name: 'Search'; fields: { 'albums': { name: 'albums'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'AlbumConnection'; ofType: null; }; } }; 'artists': { name: 'artists'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ArtistConnection'; ofType: null; }; } }; 'tracks': { name: 'tracks'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TrackConnection'; ofType: null; }; } }; }; };
    'String': unknown;
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'libraryScan': { name: 'libraryScan'; type: { kind: 'OBJECT'; name: 'LibraryScan'; ofType: null; } }; 'trackManifest': { name: 'trackManifest'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TrackManifest'; ofType: null; }; } }; }; };
    'Track': { kind: 'OBJECT'; name: 'Track'; fields: { 'album': { name: 'album'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'artist': { name: 'artist'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'artistSynonyms': { name: 'artistSynonyms'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; } }; 'delivery': { name: 'delivery'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TrackDelivery'; ofType: null; }; } }; 'discNumber': { name: 'discNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'duration': { name: 'duration'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Duration'; ofType: null; }; } }; 'format': { name: 'format'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'isLossless': { name: 'isLossless'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'path': { name: 'path'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'sourceFormat': { name: 'sourceFormat'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'title': { name: 'title'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'trackNumber': { name: 'trackNumber'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'year': { name: 'year'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'TrackConnection': { kind: 'OBJECT'; name: 'TrackConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TrackEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; 'totalCount': { name: 'totalCount'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; }; };
    'TrackDelivery': { kind: 'OBJECT'; name: 'TrackDelivery'; fields: { 'description': { name: 'description'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'isPassthrough': { name: 'isPassthrough'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'mimeType': { name: 'mimeType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'tiers': { name: 'tiers'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeliveryTier'; ofType: null; }; }; }; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'TrackEdge': { kind: 'OBJECT'; name: 'TrackEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Track'; ofType: null; }; } }; }; };
    'TrackFormat': { kind: 'INPUT_OBJECT'; name: 'TrackFormat'; isOneOf: false; inputFields: [{ name: 'losslessFormats'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; defaultValue: null }, { name: 'lossyFormats'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; }; }; defaultValue: null }, { name: 'quality'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'Quality'; ofType: null; }; }; defaultValue: null }]; };
    'TrackManifest': { kind: 'OBJECT'; name: 'TrackManifest'; fields: { 'chunks': { name: 'chunks'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TrackManifestChunk'; ofType: null; }; }; }; } }; 'done': { name: 'done'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'durationSeconds': { name: 'durationSeconds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'init': { name: 'init'; type: { kind: 'OBJECT'; name: 'TrackManifestInit'; ofType: null; } }; }; };
    'TrackManifestChunk': { kind: 'OBJECT'; name: 'TrackManifestChunk'; fields: { 'byteEnd': { name: 'byteEnd'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'byteStart': { name: 'byteStart'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'endSeconds': { name: 'endSeconds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'TrackManifestInit': { kind: 'OBJECT'; name: 'TrackManifestInit'; fields: { 'byteEnd': { name: 'byteEnd'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; 'byteStart': { name: 'byteStart'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Float'; ofType: null; }; } }; }; };
    'Void': { kind: 'OBJECT'; name: 'Void'; fields: { '_': { name: '_'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; } }; }; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: 'Subscription';
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}